### ISSUE TITLE
send() locks up for 433MHz RFM69HCW

### ISSUE THREAD

**Issue by mgrusin** [LowPowerLab/RFM69#10]
Hi, I'm Mike Grusin, one of the engineers at SparkFun Electronics.

We're about to release some breakout boards for the RFM69 module in the HCW (high power + compact) variant. We very much like your RFM69 library and are planning on using it as the baseline for our tutorials, etc.

I've run into an interesting problem that I'm still tracking down but wanted to get your insight on.

Everything has worked great with the 915MHz module. But when we run the same code on the 433MHz module, only changing the FREQUENCY definition to RF69_433MHZ, we get consistent lockups when we try to send a packet. The code is locking up in RF69.cpp line 162, which is:

while (!canSend()) receiveDone();

Interestingly, if you run the same 433MHz code on a 915MHz module, it does not lock up (though it can only barely transmit).

Also interestingly, if you run the 915MHz code on a 433MHz module, it does not lock up (and can actually get packets across a few feet). The flexibility of this chip is pretty remarkable.

I'll keep poking at it, but as you are vastly more familiar with the internals of the chip I hope you might have some ideas. I would be more than happy to send you a few of our boards if it would help.

Thanks very much for any assistance you might have, and also for your work on this library. We're big fans of the stuff you do at LowPowerLab. If you're ever interested in licensing your Moteino design to us for manufacture, let me know. (I can't promise anything, but it's a great board and I would push hard to make it so.)

Best, Mike Grusin
mike.grusin@sparkfun.com

**Comment by LowPowerLab** [comment]
Closing since there wasn't further traction on this issue.
