### ISSUE TITLE
error: 'LED' was not declared in this scope

### ISSUE THREAD

**Issue by 2ni** [LowPowerLab/RFM69#104]
When I try the examples I get the following errors while compiling with platformio. I can only compile if I delete the not used files RFM69_OTA.*

`In file included from lib/RFM69/RFM69_OTA.cpp:33:0:
lib/RFM69/RFM69_OTA.h:59:93: error: 'LED' was not declared in this scope
void CheckForWirelessHEX(RFM69& radio, SPIFlash& flash, uint8_t DEBUG=false, uint8_t LEDpin=LED);`

`lib/RFM69/RFM69_OTA.h:62:116: error: 'LED' was not declared in this scope
uint8_t HandleWirelessHEXData(RFM69& radio, uint8_t remoteID, SPIFlash& flash, uint8_t DEBUG=false, uint8_t LEDpin=LED);`

`lib/RFM69/RFM69_OTA.h:65:123: error: 'LED' was not declared in this scope
uint8_t HandleWirelessHEXDataWrapper(RFM69& radio, uint8_t remoteID, SPIFlash& flash, uint8_t DEBUG=false, uint8_t LEDpin=LED);`

**Comment by LowPowerLab** [comment]
Thanks, what board are you using?
There are definitions for AVR (328, 1284).
I [added a generic definition anyway](https://github.com/LowPowerLab/RFM69/commit/9f803629e85158b7d64b984e2ef16101deb65c85).
