### ISSUE TITLE
Listen Mode. Example

### ISSUE THREAD

**Issue by ortegafernando** [LowPowerLab/RFM69#106]
Hi, I have just started with RFM69 library to replace NRF24 modules. I want to include listen mode in my Gateway and I have tried to find an example of this mode.

I have also check LowPowerLab forum, but I can't get any complete example to use listen mode.

I have read source code and I can see several new functions if you compile with RF69_LISTENMODE_ENABLE definition.

Could you please include a simple example, for example a TxRxBlinkyListenMode.ino will be perfect.

I have doubt about how to use these new functions, after recieve a payload in RX Node what we have to do to put the node again in listen mode (or is it on listen mode automatically?)

May be there is information in a forum or similar. Please tell me, thanks.

**Comment by LowPowerLab** [comment]
Not an issue so closing this.
Listen mode is discussed there in many threads, with code examples etc.
Please ask for features or code in the forum.
Thanks

**Comment by ortegafernando** [comment]
Thanks.
