### ISSUE TITLE
Incorrect frequency calculation

### ISSUE THREAD

**Issue by Phunkafizer** [LowPowerLab/RFM69#110]
radio.setFrequency(869462UL);
results on SPI bus:
0x87 0x00 0x88 0x37 0x89 0xA5

This is wrong resulting the RFM69 not to work. Testet with Arduino micro with RFM69HCW

https://github.com/LowPowerLab/RFM69/blob/c51a7c7b99fba8f6aa09908a37330e48000e436c/RFM69.cpp#L149

**Comment by LowPowerLab** [comment]
I would not expect it to work at 869khz either ;-)
Try 869Mhz 👍

**Comment by Phunkafizer** [comment]
embarrassing... only missed it by factor 1000  ;-)
Thank you!
