### ISSUE TITLE
Unnecessary volatile?

### ISSUE THREAD

**Issue by AndrolGenhald** [LowPowerLab/RFM69#115]
Now that `interruptHandler` is no longer called from the interrupt, can `volatile` be removed from `DATA`, `DATALEN`, etc?

**Comment by LowPowerLab** [comment]
Thanks for the suggestion, yes it can be removed.
See [this commit](https://github.com/LowPowerLab/RFM69/commit/32a80592e243848b79280430e503ac522875b65f).
Will continue to use and monitor it and should make it in next release.
