### ISSUE TITLE
Crash after some time working...

### ISSUE THREAD

**Issue by ElVasquito** [LowPowerLab/RFM69#126]
After some time working, my ESP8266 sometimes crashes and this is the stack:
Decoding stack results
0x402263e2: RFM69::readReg(unsigned char) at C:\Arduino\Arduino\libraries\RFM69-master\RFM69.cpp line 473
0x4022716d: RFM69_ATC::sendFrame(unsigned short, void const*, unsigned char, bool, bool, bool, short) at C:\Arduino\Arduino\libraries\RFM69-master\RFM69_ATC.cpp line 131
0x401002c0: millis() at C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.0\cores\esp8266\core_esp8266_wiring.cpp line 188
0x40227265: RFM69_ATC::sendFrame(unsigned short, void const*, unsigned char, bool, bool) at C:\Arduino\Arduino\libraries\RFM69-master\RFM69_ATC.cpp line 87
0x40226cc5: RFM69::send(unsigned short, void const*, unsigned char, bool) at C:\Arduino\Arduino\libraries\RFM69-master\RFM69.cpp line 265
0x40228cf0: HardwareSerial::write(unsigned char const*, unsigned int) at C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.0\cores\esp8266/HardwareSerial.h line 159
0x40226ef8: RFM69_ATC::sendWithRetry(unsigned short, void const*, unsigned char, unsigned char, unsigned char) at C:\Arduino\Arduino\libraries\RFM69-master\RFM69_ATC.cpp line 173
0x40209e2b: ReceiveRadio() at C:\Arduino\ESP8266/ESP8266.ino line 1728
0x402276e7: SPIClass::beginTransaction(SPISettings) at C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.0\libraries\SPI\SPI.cpp line 145
0x40100341: __digitalWrite(uint8_t, uint8_t) at C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.0\cores\esp8266\core_esp8266_wiring_digital.cpp line 86
0x40226282: RFM69::unselect() at C:\Arduino\Arduino\libraries\RFM69-master\RFM69.cpp line 513
0x40226541: RFM69::writeReg(unsigned char, unsigned char) at C:\Arduino\Arduino\libraries\RFM69-master\RFM69.cpp line 484
0x4022663d: RFM69::setMode(unsigned char) at C:\Arduino\Arduino\libraries\RFM69-master\RFM69.cpp line 209
0x4022728d: RFM69_ATC::setMode(unsigned char) at C:\Arduino\Arduino\libraries\RFM69-master\RFM69_ATC.cpp line 57
0x40209e88: ReceiveRadio() at C:\Arduino\ESP8266/ESP8266.ino line 1738
0x4020f8be: loop() at C:\Arduino\ESP8266/ESP8266.ino line 2784

Any ideas? Line 473 is:

  uint8_t regval = SPI.transfer(0);

**Comment by LowPowerLab** [comment]
Do you have an actual reproducible bug to report?
