### ISSUE TITLE
Examples - SS_FLASHMEM/FLASH_SS/8 - where are these defined?

### ISSUE THREAD

**Issue by HeneryH** [LowPowerLab/RFM69#135]
I've seen three versions of this code and the with my current libraries installed, the #defs are not set property.  It seems like the #def is referring to the Mote pin 8. I resorted to hard coding for now.

```
#include <SPIFlash.h>         //get it here: https://www.github.com/lowpowerlab/spiflash
SPIFlash flash(FLASH_SS, 0xEF30); //EF30 for 4mbit  Windbond chip (W25X40CL)

SPIFlash flash(SS_FLASHMEM, 0xEF30); //EF30 for windbond 4mbit flash

SPIFlash flash(8, 0xEF30); //regular Moteinos have FLASH MEM on D8, MEGA has it on D4
```

**Comment by LowPowerLab** [comment]
If you use Moteinos, the FLASH_SS is defined for each board appropriately. For any other boards that exist out there the FLASH_SS can be passed in the constructor as you see in the examples.

`SPIFlash flash(CS, 0xEF30);`
