### ISSUE TITLE
ESP32 SPI2 & SPI3 Compatible Code (Cannot Use Library Without it)

### ISSUE THREAD

**Issue by ajaybnl** [LowPowerLab/RFM69#136]
I have sucessfully tested the ESP32 connected to RFM69HCW with this library by adding these lines:

in RFM69.cpp Near SPI.begin(); (Replace)
```

 #if defined(ESP32)
//Choose One SPI PORT
  SPI.begin(18,19,23,5);   //SPI3  (SCK,MISO,MOSI,CS)
// SPI.begin(14,12,13,15);   //SPI2   (SCK,MISO,MOSI,CS) 
  #else
SPI.begin();
  #endif
```

and in RFM69.h: 
```

#define RF69_IRQ_PIN    2
#define RF69_SPI_CS     5
```

Otherwise the Library does not work.

Please add these lines for ESP32.

**Comment by LowPowerLab** [comment]
@ajaybnl 
These are specific pins to some specific ESP32 variant.
Which ESP32 board are these pins from?

**Comment by ajaybnl** [comment]
> @ajaybnl
> These are specific pins to some specific ESP32 variant.
> Which ESP32 board are these pins from?

Esp32 Wroom Module (Without psram)

**Comment by ajaybnl** [comment]
![esp32-spi_pins](https://user-images.githubusercontent.com/30887303/77920856-845f9300-728e-11ea-9a93-9e42bc3750e6.jpg)

**Comment by LowPowerLab** [comment]
I am talking about ARDUINO BOARD DEFINITION. Which one is that? Not the module itself.........................

**Comment by ajaybnl** [comment]
> I am talking about ARDUINO BOARD DEFINITION. Which one is that? Not the module itself.........................

Im uploading using esp-dev-kit variant.

**Comment by ajaybnl** [comment]
Im making rfm69 and espnow gateway ( code: https://github.com/ajaybnl/esp32_rfm69_espnow_mqtt_gateway)

**Comment by ajaybnl** [comment]
Or you can impliment spiClass selection like this library: https://github.com/JF002/cfRFM69/tree/master/src

**Comment by LowPowerLab** [comment]
I understand now, OK i have merged this in the library. Done in commit 1e1236d4b4f3054d130249e6d4a2ea0a14ea98c1
Thanks

**Comment by ajaybnl** [comment]
Cheers.
