### ISSUE TITLE
Why even bother with an interrupt for DIO0?

### ISSUE THREAD

**Issue by mamama1** [LowPowerLab/RFM69#137]
Hi,

why do we even need to use a hardware interrupt of the MCU for DIO0 handling?
I'm currently changing stuff to polling the Atmega pin so I can use the interrupt for other stuff...

**Comment by LowPowerLab** [comment]
Because we need to be notified of transceiver events (like packet received) as soon as possible.
Please don't open any more issues if you just have a question, there is a [forum for that](http://forum.lowpowerlab.com/).

**Comment by mamama1** [comment]
done:
https://lowpowerlab.com/forum/rf-range-antennas-rfm69-library/why-even-bother-with-an-interrupt-for-dio0/msg27663/#msg27663
