### ISSUE TITLE
sendFrame - Why remove timout and D0 usage ?

### ISSUE THREAD

**Issue by chaveiro** [LowPowerLab/RFM69#141]
I'm questioning this chage: https://github.com/LowPowerLab/RFM69/commit/4a6f77ad479126be722ad43d4e2db1f737d15e61#diff-5ee51810c6e14f24e90fb5a9bb0fac4aR130

Have two questions:
1- Why remove the usage of D0 (using spi takes mode power, important for battery devices)
2- Why remove the timeout (if spi fails or module crashes it will be stuck here)..

**Comment by LowPowerLab** [comment]
I answered to your commit comment. Please ask questions in the forum. This place is for ISSUES not for QUESTIONS.
