### ISSUE TITLE
Support for TinyAVR Series-1 

### ISSUE THREAD

**Issue by Pjeran** [LowPowerLab/RFM69#145]
Been playing around with the Series-1 uC using the TinyMegaCore from Spencer Konde

https://github.com/SpenceKonde/megaTinyCore

Pretty impressive next generation of chips with full SPI support and up to 32Kb of program memory.  With a couple of small changes I was able to get the library working, but am not very versed in pull requests and making changes in a repository.

In RFM69.h adding:
` #elif defined(__AVR_ATtinyxy7__) // MegaTinyCore AVR Series-1
  #define RF69_PLATFORM RF69_PLATFORM_ARDUINO
 #else
  #error Platform not defined! 	
 #endif
#endif

 #elif defined(__AVR_ATtinyxy6__) // MegaTinyCore AVR Series-1
  #define RF69_PLATFORM RF69_PLATFORM_ARDUINO
 #else
  #error Platform not defined! 	
 #endif
#endif`

and properly defining CS for the SPI pins selected and a pin for the IRQ everything works well.

**Comment by LowPowerLab** [comment]
Added.
