### ISSUE TITLE
Rx Continuous Mode in FSK

### ISSUE THREAD

**Issue by AjJordy** [LowPowerLab/RFM69#151]
I was using the Continuous mode with OOK with no trouble. But when I change to FSK, it just receive noise on DIO2.

```C
// Before 
REG_DATAMODUL, RF_DATAMODUL_DATAMODE_CONTINUOUSNOBSYNC | RF_DATAMODUL_MODULATIONTYPE_OOK | RF_DATAMODUL_MODULATIONSHAPING_00

// After
REG_DATAMODUL, RF_DATAMODUL_DATAMODE_CONTINUOUSNOBSYNC | RF_DATAMODUL_MODULATIONTYPE_FSK | RF_DATAMODUL_MODULATIONSHAPING_00
``` 

What else I have to do to read the signal on DIO2 ?

**Comment by LowPowerLab** [comment]
I don't know the answer. Please do not ask how-to questions, this is for BUGS only.
