### ISSUE TITLE
radio not responding after 1.4.0 on Tiny 3217

### ISSUE THREAD

**Issue by Pjeran** [LowPowerLab/RFM69#156]
I updated the radio library to 1.4.2 on a system that was running under the 1.4.0 version of the library.  Going back to 1.4.0, it works again.  

To start debugging, I ran radio.readAllRegs() and got all ones back when running 1.4.2.  Not sure what changed in the library, and would be happy to help as I can for debugging.

**Comment by LowPowerLab** [comment]
Sorry but ATTiny is not a supported platform, you may push a commit and I will review.
