### ISSUE TITLE
Size Too big for ATtiny 8XX

### ISSUE THREAD

**Issue by EugenioMercol** [LowPowerLab/RFM69#178]
Hi!.. I triying to read the RSSI value in the air and compare against a fix value
The design and code was finished, but I have to replace de original design that contain ATMEGA328 and use Attiny8XX MCU, because ATMEGA328 is not stock available.. but.. the libraries code (RFM69.h + SPI.h + RH_RF69.h) + my code, the entire code everything joined is too big for the 8KB Flash memory size available in the Attiny 8XX.

The only that I need to do is, set frecuency and read RSSI value..

Can any help me to modify the library to avoid innecessaries function to get a smaller code?

Thanx!!!

**Comment by LowPowerLab** [comment]
Unfortunately the library was not designed with ATTiny devices in mind, we need at least the ATMega family.
So while I encourage you to try to make it work, officially there will be no support for Attiny and since there is no actual bug this issue will now be closed.
