### ISSUE TITLE
RFM69 Library Working Code with ESP32-S2 and Other ESP32 Boards.

### ISSUE THREAD

**Issue by ajaybnl** [LowPowerLab/RFM69#190]
on Line 117 of **rfm69.cpp**

Replace This:
**_spi->begin(18,19,23,5);**

With This:
** _spi->begin(SCK,MISO,MOSI,SS);**

and Now its working with ESP32-S2 and S3 Boards. (Please choose correct board from arduino ide)

**Comment by LowPowerLab** [comment]
Sorry, no such line in this library.
