### ISSUE TITLE
Sleep Mode

### ISSUE THREAD

**Issue by lukbek** [LowPowerLab/RFM69#191]
Hi, im using Moteino with RFM69CW and I've run on problem with sleepMode.
Maybe it's because my setup but I have no idea.

`void setup() { 
if (radio.initialize(FREQUENCY, NODEID, NETWORKID)) {
    radio.encrypt(ENCRYPTKEY);
    radio.enableAutoPower(ATC_RSSI);
    radio.sleep();
  }
  
  if (flash.initialize()) {
    flash.sleep();
  }
}
void loop() {
   radio.sendWithRetry(GATEWAYID, buffer, sendLen);
  radio.sleep();
  flash.sleep();

  LowPower.powerDown(SLEEP_4S, ADC_OFF, BOD_OFF);

}`

I've ommited filling the buffer and sendLen in above code. 
When I run this code, current drain is 36uA 
but with sendWithRetry commented its below 1uA.

Can You help me?

**Comment by LowPowerLab** [comment]
`radio.sleep()` should give you what you need for the radio module. Sleeping the Moteino looks good as well. The flash goes into a very low power mode already so not really necessary to call sleep on it.
I would follow a working example in the library and adapt your code from there if you still are having trouble.
Ex:
https://github.com/LowPowerLab/RFM69/tree/master/Examples/DeepSleep
