### ISSUE TITLE
Missing keywords in keywords.txt

### ISSUE THREAD

**Issue by fabienroyer** [LowPowerLab/RFM69#28]
The following keywords are missing from keywords.txt:

setNetwork
ACKRequested
setPowerLevel
readTemperature
rcCalibration
readAllRegs

Also, 'CryptFunction' is declared in keywords.txt but doesn't appear anywhere in the code and should be removed.

**Comment by LowPowerLab** [comment]
Thanks, fixed.
Most of these were not included initially and then overlooked or considered not usual functions.
