### ISSUE TITLE
Moteino Leo?

### ISSUE THREAD

**Issue by den2k** [LowPowerLab/RFM69#42]
What happened to this project?  Because I like having the USB port on the board I am working on a 32u4 based + RF69 radio board.  Been having trouble getting this to work with the Moteino RFM69 library.  Specifically I think the SS, CS, IRQ pins are not wired correctly.  Any help would be great.

**Comment by LowPowerLab** [comment]
Obsoleted.
You can use a Moteino-USB or MoteinoMEGA-USB instead.
