### ISSUE TITLE
Initialize fails on UNO

### ISSUE THREAD

**Issue by Tiebolt** [LowPowerLab/RFM69#51]
It seems the initialize function (RFM69) fails on a Arduino Uno R3 board. Tried to swap out radio's and even run the working sender on the Uno with no success. I used the default pinout (RST: 9, CS: 10; MOSI: 11; MISO: 12; CLK: 13; IRQ: 2). I'm using an RFM69HCW board on a breakout from Adafruit.

**Comment by LowPowerLab** [comment]
It works as reported by many others.
You may be missing something in wiring or not using buffering since UNO is 5V.

**Comment by Tiebolt** [comment]
So sorry. When i connected it to the uno directly (not using the test shield) it worked right away. So i'm writing this blushing as hell ;)
