### ISSUE TITLE
SPCR was not declared?

### ISSUE THREAD

**Issue by solars** [LowPowerLab/RFM69#53]
Hi there,

Trying to get started with RFM69, but if I try to compile a basic example I get:
https://gist.github.com/solars/1e52718dacacdb018de3efc62206d9f8

Any idea how to solve this?

Thanks a lot

**Comment by LowPowerLab** [comment]
You need to do this from the ArduinoIDE, the SPCR is a core register defined in the AVR classes.

**Comment by solars** [comment]
How do you mean? I'm starting it in the arduino ide - but it's a wemos d1 mini

**Comment by LowPowerLab** [comment]
What's your target board?

**Comment by solars** [comment]
The wemos d1 mini

**Comment by LowPowerLab** [comment]
Sorry but I don't know what that is of if that has a SPCR.

**Comment by solars** [comment]
It's a ESP8266 board, not sure either: https://www.wemos.cc/product/d1-mini.html

**Comment by LowPowerLab** [comment]
Oh ok, that won't have an SPCR.

**Comment by solars** [comment]
Does this mean the lib won't work? And does this depend on the board? I read that in general the ESP8266 works. Thanks a lot for your help

**Comment by LowPowerLab** [comment]
I know others use the ESP8266 with RFM69 using this library. You may want to check www.lowpowerlab.com/forum

**Comment by LowPowerLab** [comment]
BTW the SPCR checks are wrapped in `#ifdefs`:
`#if defined (SPCR) && defined (SPSR)`
So you should never have a compile problem even if SPCR is not defined.
