### ISSUE TITLE
Gateway example migth not request ACK from every node

### ISSUE THREAD

**Issue by cheops** [LowPowerLab/RFM69#55]
The Gateway example requests ACK from every 3th packet received. Depending on the sending frequency and the number of remote nodes, it might not requests ACKs from alle the remotes. Maybe an array to track packet numbers per node is more accurate.

**Comment by LowPowerLab** [comment]
This is intentional and not an issue. The Gateway example is just for illustrating how to use the library with the radio. The library will only request an ACK from the node that last sent a message, the assumption is that node is listening and able to send an ACK.
