### ISSUE TITLE
RFM69HCW: transmit in PA0 mode?

### ISSUE THREAD

**Issue by gcl8a** [LowPowerLab/RFM69#59]
[new to github -- apologies if this isn't the place to ask this]

Thanks for the library.

I'm trying to transmit in PA0 mode and it doesn't work. You have in your code that:

`"// for RFM69HW only: you must call setHighPower(true) after initialize() or else transmission won't work"`

Thought I don't fully understand the differences between H, HW, and HCW, I tried calling `setHighPower(false)` and, indeed, it doesn't appear to transmit.

Do you know why this is? Is it possible to transmit in PA0 mode with some different settings? Basically, I'm trying to reduce power consumption on transmit, moreso than with `setPowerLevel()`.

**Comment by LowPowerLab** [comment]
Please [see this](https://www.andrehessling.de/2015/02/07/figuring-out-the-power-level-settings-of-hoperfs-rfm69-hwhcw-modules/) for information.
Any other questions [in the forum](https://lowpowerlab.com/forum) please.
