### ISSUE TITLE
RSSI

### ISSUE THREAD

**Issue by spa-sam** [LowPowerLab/RFM69#62]
The module RFM69HW. If the mode of radio.setHighPower(), rssi shows about 100 regardless of the signal strength. It is only in the receive mode to enable setHighPower(false),then everything responds as it should. But again setHighPower(true) as the rssi again about 100 and does not change.

**Comment by LowPowerLab** [comment]
RSSI means ***receive*** signal strength indicator. Receive means you need to be in **_receive_** mode obviously.

**Comment by spa-sam** [comment]
Then it can be noted in the examples?

**Comment by LowPowerLab** [comment]
I guess it could but I think everyone understands RSSI should only be read in receive mode.
This is also noted in the transceiver datasheet.
