### ISSUE TITLE
atmega128

### ISSUE THREAD

**Issue by spa-sam** [LowPowerLab/RFM69#63]
Connected rfm69 to atmega128
The problem with the definition of Interrupt. pin 4 is what is the interrupt number? Someone rfm69 connected to the atmega128. https://github.com/MCUdude/MegaCore

#define RFM69_CS 8
#define RFM69_IRQ 4 //pin
#define RFM69_IRQN 4// ?

RFM69 radio = RFM69(RFM69_CS, RFM69_IRQ, true, RFM69_IRQN);

**Comment by LowPowerLab** [comment]
Not clear what the problem is. You can set the interrupt you use via the constructor.
