### ISSUE TITLE
pinMode for interrupt pin

### ISSUE THREAD

**Issue by hauler** [LowPowerLab/RFM69#64]
Guys, please add setting of interrupt pin mode to INPUT somewhere -- I've just killed two days trying to figure out why radio.send hangs...

**Comment by LowPowerLab** [comment]
Thanks, I have never seen a problem with this, what MCU/hardware are you using and what sketch?

**Comment by hauler** [comment]
I'm using RFM69HW and some chinese copy (I guess) or [Sparkfun's Pro Micro](https://learn.sparkfun.com/tutorials/pro-micro--fio-v3-hookup-guide)

**Comment by LowPowerLab** [comment]
Well .. sorry but this was never a problem on genuine Moteino hardware.
