### ISSUE TITLE
HCW vs HW

### ISSUE THREAD

**Issue by consolacion** [LowPowerLab/RFM69#69]
Maybe more a question than an issue:
What is exactly the difference between the HCW and the HW version, as they both are +20dB? Just the pinout?
should the 
#ifdef IS_RFM69HW
  radio.setHighPower(); //only for RFM69HW!
#endif

also be set for the HCW version?

**Comment by LowPowerLab** [comment]
Yes they are only different in pinout and size, but otherwise work identically, both 20dBm.
I will try to adjust all the samples so its less confusing.
