### ISSUE TITLE
On board GPIO

### ISSUE THREAD

**Issue by fabltd** [LowPowerLab/RFM69#74]
How do you access the GPIO outs from the RFM69HCW PCB ?

**Comment by LowPowerLab** [comment]
DIO0 is connected to D2 (INT0) interrupt pin for use in the library.
The others you will have to connect directly from the RFM module.
The MoteinoMEGA has jumper options to connect DIO1 and DIO2 and RST.

**Comment by fabltd** [comment]
Hi

Do you support the other gpio pins.

I want to add a dip switch for setting the network ids.

Thanks

Regards,
Jeremy Turner
Managing Director
Jeremy@fabcontrols.co.uk
Mobile 0797 131 4661

On 17 Apr 2017, at 13:34, Felix Rusu <notifications@github.com> wrote:

DIO0 is connected to D2 (INT0) interrupt pin for use in the library.
The others you will have to connect directly from the RFM module.
The MoteinoMEGA has jumper options to connect DIO1 and DIO2 and RST.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LowPowerLab/RFM69/issues/74#issuecomment-294475897>,
or mute
the thread

**Comment by LowPowerLab** [comment]
That doesn't have much to do with the library. Do that on your MCU GPIO.

**Comment by fabltd** [comment]
Hi

I am short on pins so hoped I could use the extra ones on the rfm69 .

Regards,
Jeremy Turner
Managing Director
Jeremy@fabcontrols.co.uk
Mobile 0797 131 4661

On 17 Apr 2017, at 14:28, Felix Rusu <notifications@github.com> wrote:

That doesn't have much to do with the library. Do that on your MCU GPIO.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LowPowerLab/RFM69/issues/74#issuecomment-294485463>,
or mute
the thread

**Comment by LowPowerLab** [comment]
The radio radio pins are not for general use but they have specific functions. See the sx1231h datasheet.
You can use a MoteinoMEGA for extra pins. BTW the analog pins on any Moteino can also be used as digital pins.

**Comment by fabltd** [comment]
Thanks

Regards,
Jeremy Turner
Managing Director
Jeremy@fabcontrols.co.uk
Mobile 0797 131 4661

On 17 Apr 2017, at 14:34, Felix Rusu <notifications@github.com> wrote:

The radio radio pins are not for general use but they have specific
functions. See the sx1231h datasheet.
You can use a MoteinoMEGA for extra pins. BTW the analog pins on any
Moteino can also be used as digital pins.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LowPowerLab/RFM69/issues/74#issuecomment-294486337>,
or mute
the thread
