### ISSUE TITLE
millis rollover

### ISSUE THREAD

**Issue by rainoko** [LowPowerLab/RFM69#78]
here and there is are code that checks some time past with similar
while (!canSend() && millis() - now < RF69_CSMA_LIMIT_MS) receiveDone();
But millis function rollover every ~49 days, this means after that there are glitches where code keeps running another 49 days because now is bigger than millis()

**Comment by LowPowerLab** [comment]
Thanks but no, it does not do that. I will let you do the math.

**Comment by rainoko** [comment]
ofcourse didn't notice that uint are used.
