### ISSUE TITLE
Why is this line commented out?

### ISSUE THREAD

**Issue by whmountains** [LowPowerLab/RFM69#83]
https://github.com/LowPowerLab/RFM69/blob/928de01a2b0ffc21d0dff935694641c04d6b9041/RFM69_OTA.cpp#L67

Wouldn't it be dangerous to leave a partially written image to Flash?  It would be guaranteed to brick the Moteino on the next reset.

**Comment by LowPowerLab** [comment]
No, it won't brick anything. At that point in time the image may be partial but without the all important header (which includes a byte count that can only be calculated once the whole image is received), the bootloader leaves it alone and jumps to the main sketch.
This is more for debugging, once you wrote a partial image and then transfer fails, its more useful to lave it there and look at it, then just erase all evidence of what went wrong.
Reference:
https://github.com/LowPowerLab/RFM69/blob/928de01a2b0ffc21d0dff935694641c04d6b9041/RFM69_OTA.cpp#L210
https://github.com/LowPowerLab/DualOptiboot/blob/master/Optiboot.c#L581
