### ISSUE TITLE
Node crashes on radio.sleep()

### ISSUE THREAD

**Issue by markvdlee** [LowPowerLab/RFM69#85]
Hi, I am making a home automation sensor network using RFM69's. Set-up is working great so far but I am having a small problem...

I'm using the example "DeepSleep_usingLowPowerLibrary" to test the sleep power consumption of my nodes. Problem is: The example is not running on my sensor node's.
 
I first tried using only the `LowPower.powerDown(SLEEP_8S, ADC_OFF, BOD_OFF);` statement to test the ATmega328 sleep functionality, witch works perfect. 

Second test was to put also the Radio in sleep mode using the `radio.sleep();` statement. But the moment the Arduino executes that line of code it won't continue. 
If I place the `radio.sleep();` statement in the void loop I got the same problem. The arduino stops working when it arrives at the sleep line... 
I tested the above with the serial monitor and proper capacitors/power supply!
Note: I am not using the Flash Mem functionality in the "DeepSleep_usingLowPowerLibrary" so I just commented the `#define WITH_SPIFLASH` line out

I would really want to know if someone has the same problem or has a solution! 
Thanks in advance

**Comment by LowPowerLab** [comment]
I suggest posting this in the [LPL forum](https://lowpowerlab.com/forum). The `radio.sleep()` function works, that is for sure. I would check your hardware or have another test on a different set of boards.
