### ISSUE TITLE
Why no hardware address filtering?

### ISSUE THREAD

**Issue by Imlerih** [LowPowerLab/RFM69#88]
Hello again. I`m sorry for being annoying, but I still have some questions. I`ve found the way how to enable harware address filtering, but I`m interested why you decided to tunt it off and how can it effect if I enable it.

**Comment by LowPowerLab** [comment]
Like I said, in your previous thread, this is discussed in the forum, please search for "address filtering" and you can see various threads that touch on the subject. The bottom line is you cannot listen to other nodes with hardware address filtering and more control is preferred in the library, hence it was implemented that way.
Please do not open **Issues** if you do not have an **Issue** to report. Please use the forum to discuss and ask questions.
