### ISSUE TITLE
Using an RFM69HW with an Arduino MKR GSM 1400

### ISSUE THREAD

**Issue by johannstieger** [LowPowerLab/RFM69#90]
Hi, I wanna use a Arduino MKR GSM 1400 (see https://store.arduino.cc/mkr-gsm-1400) as a gateway. Is it possible to use your RFM69 library with this ARM-based Arduino? The Arduino does have a SPI-Interface with MISO on pin 10, SCK on pin 9 and MOSI on pin 8. On which pins should I connect NSS/SS and DIO0?

Thank you very much, Johann

**Comment by LowPowerLab** [comment]
I do not know. You may ask in the forum please.
